import AppKit

final class ClipboardMonitor {
    typealias SourceApplication = (name: String?, bundleID: String?)

    enum Limits {
        static let maximumTextBytes = 1 * 1_024 * 1_024
        static let maximumImageBytes = 8 * 1_024 * 1_024
        static let maximumFileCount = 100
    }

    var onCapture: ((ClipboardPayload, String?, String?) -> Void)?
    var isPaused = false

    private let pasteboard: NSPasteboard
    private let sourceApplicationProvider: () -> SourceApplication?
    private var timer: Timer?
    private var lastChangeCount: Int

    private let ignoredTypes = Set([
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ])

    init(
        pasteboard: NSPasteboard = .general,
        sourceApplicationProvider: @escaping () -> SourceApplication? = {
            ClipboardMonitor.frontmostSourceApplication()
        }
    ) {
        self.pasteboard = pasteboard
        self.sourceApplicationProvider = sourceApplicationProvider
        self.lastChangeCount = pasteboard.changeCount
    }

    func start() {
        guard timer == nil else { return }
        let timer = Timer(timeInterval: 0.35, repeats: true) { [weak self] _ in
            self?.poll()
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func write(_ payload: ClipboardPayload) {
        pasteboard.clearContents()

        switch payload {
        case .text(let text):
            pasteboard.setString(text, forType: .string)
        case .image(let data, let type):
            pasteboard.setData(data, forType: NSPasteboard.PasteboardType(type))
        case .files(let paths):
            let URLs = paths.map { NSURL(fileURLWithPath: $0) }
            pasteboard.writeObjects(URLs)
        }

        lastChangeCount = pasteboard.changeCount
    }

    func poll() {
        let currentChangeCount = pasteboard.changeCount
        guard currentChangeCount != lastChangeCount else { return }
        lastChangeCount = currentChangeCount
        guard !isPaused, !containsIgnoredType else { return }
        let sourceApplication = sourceApplicationProvider()
        guard let payload = readPayload() else { return }
        onCapture?(payload, sourceApplication?.name, sourceApplication?.bundleID)
    }

    private var containsIgnoredType: Bool {
        let currentTypes = Set(pasteboard.types ?? [])
        return !currentTypes.isDisjoint(with: ignoredTypes)
    }

    private static func frontmostSourceApplication() -> SourceApplication? {
        guard let application = NSWorkspace.shared.frontmostApplication,
              application.processIdentifier != ProcessInfo.processInfo.processIdentifier else {
            return nil
        }

        if let ownBundleID = Bundle.main.bundleIdentifier,
           application.bundleIdentifier == ownBundleID {
            return nil
        }

        return (application.localizedName, application.bundleIdentifier)
    }

    private func readPayload() -> ClipboardPayload? {
        if pasteboard.availableType(from: [.fileURL]) != nil,
           let objects = pasteboard.readObjects(
               forClasses: [NSURL.self],
               options: [.urlReadingFileURLsOnly: true]
           ) as? [URL],
           !objects.isEmpty,
           objects.count <= Limits.maximumFileCount {
            return .files(objects.map(\.path))
        }

        if let imageType = pasteboard.availableType(from: [.png, .tiff]),
           let data = pasteboard.data(forType: imageType),
           !data.isEmpty,
           data.count <= Limits.maximumImageBytes {
            return .image(data: data, pasteboardType: imageType.rawValue)
        }

        if let text = pasteboard.string(forType: .string),
           !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
           text.utf8.count <= Limits.maximumTextBytes {
            return .text(text)
        }

        return nil
    }
}
